### ISSUE TITLE
Internal error con usuarios que no son administrador

### ISSUE THREAD

**Issue by Samadhibin** [danielanguita/redmine_inventory_manager#23]
Al entrar al inventory manager como administrador no hay ningún problema en ninguna pestaña.

Con los usuarios que no son administrador hay problemas.
Las pestañas stock de inventario, bodega e informes funcionan.
Las pestañas Movimientos, productos, categorias, proveedores dan internal error.

En "/var/log/redmine/default/production.log" se encuentra lo siguiente:
_Started GET "/redmine/inventory/movements" for 192.168.1.20 at 2017-01-18 16:25:13 +0100
Processing by InventoryController#movements as HTML
  Current user: user (id=6)
Completed 500 Internal Server Error in 41ms (ActiveRecord: 12.3ms)

ActiveRecord::StatementInvalid (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':conditions=>"user_manager_id = 6"}) FROM `inventory_warehouses`' at line 1: SELECT COUNT({:conditions=>"user_manager_id = 6"}) FROM `inventory_warehouses`):
  plugins/redmine_inventory_manager/app/controllers/inventory_controller.rb:229:in `user_has_warehouse_permission'
  plugins/redmine_inventory_manager/app/controllers/inventory_controller.rb:251:in `movements'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'_

La instalación de redmine::
_Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  advanced_roadmap               0.10.1
  easy_gantt                     1.7
  redmine_agile                  1.4.2
  redmine_checklists             3.1.5
  redmine_gc_sync                1.0.0
  redmine_inventory_manager      0.9_

He buscado en perfiles y permisos pero no encuentro nada.

**Comment by w0www** [comment]
um.... Lo reviso y te digo algo, dejame un par de días vale? Si encuentras la solución antes y es un bug comentala para arreglarla.

**Comment by Samadhibin** [comment]
Encontré donde estaba el problema y lo he parcheado para que funcione. Pero no es que sea una solución muy elegante:
He cambiado el código de "plugins/redmine_inventory_manager/app/controllers/inventory_controller.rb" cambiando todas las lineas de "@has_permission = XXXXXXXXXXX" por "@has_permission = true"

**Comment by w0www** [comment]
Ok, revisare de todas formas el problema ya que estoy intentado sacar tiempo para dejar este plugin mas fino. 👍

**Comment by w0www** [comment]
Dejo abierta la ISSUE mientras tanto ;)

**Comment by Samadhibin** [comment]
Muchas gracias por contestar tan rápido!!

**Comment by urvil** [comment]
Hi,
Any final resolution to this.

Additional information to @Samadhibin information as below.
At line number 251(same line) there is a function call 
"ser_has_warehouse_permission(current_user.id, nil)"
this nil value can be the cause ?
