### ISSUE TITLE
Error during installation/migration

### ISSUE THREAD

**Issue by margru** [danielanguita/redmine_inventory_manager#29]
When running 
`bundle exec rake redmine:plugins NAME=redmine_inventory_manager RAILS_ENV=production`
I got the following error:
<pre>
StandardError: An error has occurred, all later migrations canceled:
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
  class CreateInventoryParts < ActiveRecord::Migration[4.2]
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:528:in `inherited'
/opt/redmine-4.0.3/plugins/redmine_inventory_manager/db/migrate/001_create_inventory_parts.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:986:in `load_migration'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:982:in `migration'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1350:in `use_transaction?'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1342:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1262:in `each'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine-4.0.3/lib/redmine/plugin.rb:504:in `up'
/usr/local/rvm/gems/ruby-2.6.3/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine-4.0.3/lib/redmine/plugin.rb:536:in `migrate_plugin'
/opt/redmine-4.0.3/lib/redmine/plugin.rb:477:in `migrate'
/opt/redmine-4.0.3/lib/redmine/plugin.rb:488:in `migrate'
/opt/redmine-4.0.3/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/opt/redmine-4.0.3/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.6.3/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
</pre>

Using:
  Redmine version  4.0.3.stable
  Ruby version 2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version 5.2.2.1

Is this plugin compatible with Redmine 4?

**Comment by manusanchezr** [comment]
[migration_error.txt](https://github.com/danielanguita/redmine_inventory_manager/files/4029667/migration_error.txt)

Hola Daniel, yo tengo el mismo problema que 'magru' con la versión 4 de Redmine. ¿Es realmente un problema de compatibilidad? Si es así ¿Se va a corregir en breve?

Gracias y un saludo,
Manuel

**Comment by danielanguita** [comment]
Hola/Hi,

Este plugin no es compatible con Redmine 4 aun, pero si quieren contribuir al codigo puedo darles acceso de desarrollo, seguramente debe haber alguna compatibilidad simple de resolver.

This plugin is not compatible with Redmine 4 yet, but if you want to fix it I'll be happy to give you access to develop, most likely the compatibility issue is simple to solve.

Saludos

**Comment by smlabonia** [comment]
Daniel, si quieres puedes darme acceso de desarrollador. 

Lo único que hay que hacer es agregar [4.2] al final de la primera línea de cada migration.

**Comment by danielanguita** [comment]
Ok, te dare accceso.

**Comment by emilianobaum** [comment]
Efectivamente funciona con la version 5 agregando al final de las class [5.0] en la ubicacion:

`$ plugins/redmine_inventory_manager/db/migrate/`
